name: 'Test: Contracts'

on:
  push:
    branches:
      - '**'
jobs:
  test-contracts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 240
          max_attempts: 3
          retry_on: error
          command: yarn

      - name: Run tests
        run: yarn jest
